### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by matbrady** [kitajchuk/contentful-express#8]
First off, cool project! On to the issue...
Likely something I've missed but running `contentful-express sync` wont download any entries. 
The command successfully runs. here's the output:
```
> contentful-express sync
> lager Dropping lowdb databases...
> lager Sync: Space Test...
> lager Sync: Content Type: Post...
> lager Sync: Content Type: Author...
> lager Sync: Content Type: Category...
> lager Sync: Content Type: Event...
> lager Sync: Assets...
> lager Sync: Entry: 5JQ715oDQW68k8EiEuKOk8: 1kUEViTN4EmGiEaaeC6ouY...
```
Shouldn't I be expecting the `db/entries.json` file to be updated after sync? This is the result after sync:
```
{
  "2wKn6yEnZewu2SCCkus4as": [],
  "1kUEViTN4EmGiEaaeC6ouY": [],
  "5KMiN6YPvi42icqAUQMCQe": [],
  "event": []
}
```
I am able to view the entries through the [Contentful Discover App](https://contentful.github.io/discovery-app-react/entries/by-content-type/event/501UcfPToQOAOw6YqgcqSq?access_token=78fa2e2708242aaa5143f1f4f13e8bfb89e37a591cfde75ed6a05a80e06221d3&preview_access_token=46ed2ad0212d5ebd137c635b00d376b0924e09737f104269119c22d3f4731a9c&space_id=b3uwwo7fexs2). 
Probably something simple but I was curious if you had some pointers. LMK if you need any more environment/config information. Thanks for your help!!

**Comment by kitajchuk** [comment]
Hmm. I can take a look. I haven't been keeping up with this module because I'm using another service right now - https://prismic.io. The [same tool](https://github.com/kitajchuk/prismic-express) exists for that as well, I just haven't been making the same updates here.

**Comment by kitajchuk** [comment]
@matbrady I was able to sync successfully using my production api key and my space ID. Is that what you are using in your config.js?

**Comment by matbrady** [comment]
@kitajchuk yeah, I copied the production api key and space ID directly from the contentful dashboard. The sync runs but doesn't pull down any data.

**Comment by kitajchuk** [comment]
Looks like you're entry sync is weird. It should be trying to sync based on `customType`. But yours shows `Entry: ID: ID` which is weird. When I sync my contentful space I get this. Notice the `Sync: Entry: 1YalphBvfWYkY8EmiKkEUS: category...`.

```shell
> lager Dropping lowdb databases...
> lager Sync: Assets...
> lager Sync: Space Index.la...
> lager Sync: Content Type: City...
> lager Sync: Content Type: Artist...
> lager Sync: Content Type: Type...
> lager Sync: Content Type: Region...
> lager Sync: Content Type: Agency...
> lager Sync: Content Type: Feature...
> lager Sync: Content Type: Category...
> lager Sync: Entry: 2A779ofHtG8k86ey6MGqCe: type...
> lager Sync: Entry: 3EpAn6cwYgGWA224agI6Sk: category...
> lager Sync: Entry: 58fxaBYPLOAKoy8GYGwoKs: category...
> lager Sync: Entry: 2amG5vuKKgkKWosAQk8E02: region...
> lager Sync: Entry: 3vKlkmLebY8UgGOiyEaWoY: agency...
> lager Sync: Entry: 2a0p9ZLDIAYwyeo444wuMi: category...
> lager Sync: Entry: 6rR3VhlpEAcYGyIgy2qcm0: region...
> lager Sync: Entry: 7fgAymqWLSIymaGiyUowoa: type...
> lager Sync: Entry: 2XhMxN0t5C4YYE2Kaqw0YG: category...
> lager Sync: Entry: 1tdJcj38kwug4ay4eqAuwA: region...
> lager Sync: Entry: 4XmbKUBXxmQKKI8K66ogQC: category...
> lager Sync: Entry: 5YLUy5PSEMGQIqAaYqKIoM: type...
> lager Sync: Entry: 6CdHGJnwR2m0UUAWKUUUc4: category...
> lager Sync: Entry: 38SJEWaly8iiIqoKgIQUW4: region...
> lager Sync: Entry: 2zZ64AahkU4iOgYcW4Wqi8: city...
> lager Sync: Entry: 1YalphBvfWYkY8EmiKkEUS: category...
> lager Sync: Entry: 1sQrBFXZjmSCgCAMsyIOq2: category...
> lager Contentful sync success!
```

**Comment by matbrady** [comment]
Yeah I thought that was odd. I think those are IDs associated with the example content types created by contentful when you create a demo space. I'll try with new space from scratch and see if the sync still fails.

**Comment by kitajchuk** [comment]
Ok. I haven't tried with the demo content before. I would try making your own content types and seeing if that works.

**Comment by matbrady** [comment]
Yep that seemed to be the issue. I created a new blank space with one test content type and the sync worked correctly! Not sure what's up with the example content types. May be worth mentioning the conflict in the readme. Thanks for your help!
```
Dropping lowdb databases...
Sync: Content Type: foobar...
Sync: Assets...
Sync: Space contentful-express...
Sync: Entry: 5Gu2lUZjpeeIsMaigQamc0: foobar...
Contentful sync success!
```
